"""변경사항 설명

Revision ID: 644a1c9a971c
Revises: 
Create Date: 2024-11-30 18:24:13.704788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644a1c9a971c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date', sa.VARCHAR(length=100), nullable=False),
    sa.Column('company', sa.VARCHAR(length=100), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=200), nullable=True),
    sa.Column('wordcloud_image', sa.VARCHAR(length=200), nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
