"""add notification table

Revision ID: d412aa6a54c2
Revises: 1b7bf586f36f
Create Date: 2025-05-18 00:04:55.150892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd412aa6a54c2'
down_revision = '1b7bf586f36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookmark')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('keyword',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('wordcloud_image',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=300),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('wordcloud_image',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('keyword',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               nullable=False)

    op.create_table('bookmark',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('news_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
